AllCops:
  Include:
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - examples
    - pio.gemspec
    - tasks/*.rake
  Exclude:
    - bin/*
    - vendor/**/*

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/DotPosition:
  EnforcedStyle: trailing
