AllCops:
  Includes:
    - Gemfile
    - Guardfile
    - Rakefile
    - examples
    - pio.gemspec
    - tasks/*.rake

# Don't require magic comment at the top of every file
Encoding:
  Enabled: false
