AllCops:
  Include:
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - examples
    - pio.gemspec
    - tasks/*.rake
  Exclude:
    - bin/*
    - vendor/**/*

Metrics/LineLength:
  Exclude:
    - 'fixtures/**/*.rb'
    - 'spec/support/*.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/DotPosition:
  EnforcedStyle: trailing
